//
// Autogenerated by Thrift Compiler (0.16.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = module.exports = {};
ttypes.SMALL_INT64 = new Int64(42);
ttypes.MAX_JS_SAFE_INT64 = new Int64(9007199254740991);
ttypes.MIN_JS_SAFE_INT64 = new Int64(-9007199254740991);
ttypes.MAX_JS_SAFE_PLUS_ONE_INT64 = new Int64('20000000000000');
ttypes.MIN_JS_SAFE_MINUS_ONE_INT64 = new Int64('ffe0000000000000');
ttypes.MAX_SIGNED_INT64 = new Int64('7fffffffffffffff');
ttypes.MIN_SIGNED_INT64 = new Int64('8000000000000000');
ttypes.INT64_LIST = [new Int64(42),new Int64(9007199254740991),new Int64(-9007199254740991),new Int64('20000000000000'),new Int64('ffe0000000000000'),new Int64('7fffffffffffffff'),new Int64('8000000000000000')];
ttypes.INT64_2_INT64_MAP = {
  "9007199254740991" : new Int64(9007199254740991),
  "9007199254740992" : new Int64('20000000000000'),
  "9223372036854775807" : new Int64('7fffffffffffffff'),
  "-9007199254740991" : new Int64(-9007199254740991),
  "-9007199254740992" : new Int64('ffe0000000000000'),
  "-9223372036854775808" : new Int64('8000000000000000'),
  "42" : new Int64(42)
};
