//
// Autogenerated by Thrift Compiler (0.16.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');


declare var SMALL_INT64: Int64;

declare var MAX_JS_SAFE_INT64: Int64;

declare var MIN_JS_SAFE_INT64: Int64;

declare var MAX_JS_SAFE_PLUS_ONE_INT64: Int64;

declare var MIN_JS_SAFE_MINUS_ONE_INT64: Int64;

declare var MAX_SIGNED_INT64: Int64;

declare var MIN_SIGNED_INT64: Int64;

declare var INT64_LIST: Int64[];

declare var INT64_2_INT64_MAP: any;
